# -*- coding: utf-8 -*-
"""2020.07.10 task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-CRJEY0sf-wsNvg-blrdwf7Xqkl1BsN2
"""

#NEESMU AUTORS, BET MĒĢINU SAPRAST KĀ TAS STRĀDĀ

n=int(input("Enter number of rows: "))   #Ievadiet līniju skaitu
a=[] # a ir list
for i in range(n): #norāda i iespējamo diapazonu
    a.append([])   #a mainīgajam izveido apakš-listus
    a[i].append(1) #a mainīgajam i noteiktajā diapazonā pievieno skaitli 1

    for j in range(1,i): #norāda j iespējamās vērtības diapazonā no 1 lidz i jeb bezgalīgi kamēr būs norādīts līniju skaits.
        a[i].append(a[i-1][j-1]+a[i-1][j]) #nosaka vērtību skaitli trijstūrī ko iegūst saskaitot divus skaitļus, kas atrodas virs tā, tiek izveidoti list konteineri.
    if(n!=0):
        a[i].append(1)

for i in range(n):
    print("   "*(n-i),end=" ",sep=" ") #norāda vajadzīgo print formātu, lai izveidotu simetrisku trijstūri
    for j in range(0,i+1):
        print('{0:6}'.format(a[i][j]),end=" ",sep=" ")
    print()